In [1]:
import os
import pandas as pd
import networkx as nx
from termcolor import colored
from loguru import logger
from graph_tool.all import *

/home/ron/miniconda3/envs/vl-bert/lib/python3.6/site-packages/graph_tool/draw/cairo_draw.py:1494: RuntimeWarning: Error importing Gtk module: No module named 'gi'; GTK+ drawing will not work.
  warnings.warn(msg, RuntimeWarning)


In [47]:

def walk_all_path(G, paths):
    for path in paths:
        path_str = ''
        
        for i, vid in enumerate(path):
            if i == 0:
                v_lab = colored(G.vp['label'][G.vertex(path[0])], color='green')
                edge = G.edge(G.vertex(vid), G.vertex(path[1]))
#                 e_lab = G.ep['property_id'][edge]
                e_lab = ''
                path_str += f'{v_lab} -{e_lab}-> '
            elif i == len(path) - 1:
                v_lab = colored(G.vp['label'][G.vertex(vid)], color='green')
                path_str += f'{v_lab}'
            else:
                v_lab = colored(G.vp['label'][G.vertex(vid)], color='blue')
                edge = G.edge(G.vertex(vid), G.vertex(path[i - 1]))
#                 e_lab = G.ep['property_id'][edge]
                e_lab = ''
                path_str += f'{v_lab} -{e_lab}-> '
        
        print(path_str)

In [2]:
openmp_set_num_threads(16)

In [3]:
graph_file = "/home/ron/Documents/wikidata.xml.gz"

In [4]:
G = load_graph(graph_file)

In [8]:
jewish = find_vertex(G, G.vertex_properties["id"], 7325)[0]
nazi = find_vertex(G, G.vertex_properties["id"], 574578)[0]




In [58]:
mosque = find_vertex(G, G.vertex_properties["id"], 32815)[0]
gay = find_vertex(G, G.vertex_properties["id"], 592)[0]
stoning = find_vertex(G, G.vertex_properties["id"], 193777)[0]
firearm = find_vertex(G, G.vertex_properties["id"], 12796)[0]
mass_shooting = find_vertex(G, G.vertex_properties["id"], 21480300)[0]

In [6]:
G.set_directed(False)

In [59]:
paths = list(all_shortest_paths(G, mass_shooting, mosque))

In [60]:
paths

[array([14293184,   626432,   125412,  1071014,      143,      853,
          396928,    30771], dtype=uint64),
 array([14293184,   626432,   125412,   560718,      167,      853,
          396928,    30771], dtype=uint64),
 array([14293184,   626432,   125412,   560718,      167,      853,
          396928,    30771], dtype=uint64),
 array([14293184,   626432,   125412,   497493,    32096,  1101425,
          396928,    30771], dtype=uint64),
 array([14293184,   626432,   125412, 12777948,    32096,  1101425,
          396928,    30771], dtype=uint64)]

In [61]:
walk_all_path(G, paths)

mass shooting --> mass murder --> murder --> voluntary manslaughter --> Russia --> Afghanistan --> emblem of Afghanistan --> mosque
mass shooting --> mass murder --> murder --> Strafgesetzbuch --> Germany --> Afghanistan --> emblem of Afghanistan --> mosque
mass shooting --> mass murder --> murder --> Strafgesetzbuch --> Germany --> Afghanistan --> emblem of Afghanistan --> mosque
mass shooting --> mass murder --> murder --> Brockhaus and Efron Encyclopedic Dictionary --> Russian Empire --> Emirate of Afghanistan --> emblem of Afghanistan --> mosque
mass shooting --> mass murder --> murder --> Small Brockhaus and Efron Encyclopedic Dictionary --> Russian Empire --> Emirate of Afghanistan --> emblem of Afghanistan --> mosque


In [42]:
eppid = G.ep['property_id']

In [43]:
arr = eppid.get_array()

In [44]:
arr is None

False

In [46]:
arr[:100]

PropertyArray([  31,  279,  398,  398,  398,  398,  398,  398,  398,  461,
                527,  527,  793,  793,  793,  793,  793,  793,  793,  828,
                910, 1343, 1419, 1424, 1552, 1889, 1889, 2184, 2579, 2670,
               2670, 2670, 2670, 2670, 2670, 2670, 5008,   31,  138,  163,
                170,  170,  276,  361,  397,  398,  398,  398,  398,  398,
                398,  398,  460,  461,  522,  522,  527,  527,  527,  527,
                527,  527,  527,  527,  527,  527,  527,  610,  610,  706,
                910,  913, 1343, 1343, 1343, 1343, 1343, 1343, 1419, 1552,
               1552, 1552, 1557, 1589, 1889, 1889, 2184, 2184, 2579, 2579,
               2579, 2633, 2959, 5008, 5125,   31,  279,  279,  279,  361],
              dtype=int32)

In [51]:
walk_all_path(G, [G.get_all_neighbors(stoning)])

execution method --> capital punishment --> Real'nyj slovar' klassicheskih drevnostej po Ljubkeru --> WikiProject Human rights --> Stephen --> Petronius Maximus --> Ramon Llull --> James the Just --> Saint Matthias --> Hamza Hakimzade Niyazi --> Ansverus --> Olympias --> Sakineh Mohammadi Ashtiani --> Anthony Neyrot --> Ghofrane Haddaoui --> Onesimus --> Philotas --> Lucius Appuleius Saturninus --> Prusias II of Bithynia --> Tarcisius --> Stoning of Du'a Khalil Aswad --> Axel von Fersen the Younger --> Archippus --> Blot-Sweyn --> Soraya Manutchehri --> Philemon --> Aulus Postumius Albinus --> Pierina Morosini --> Palladius --> Hesychius of Cazorla --> Abibos of Nekresi --> Hunald of Aquitaine --> Saint Eskil --> Saint Telemachus --> Saint Warinus --> Desiderius of Vienne --> Publius Postumius Albus Regillensis --> Raynerius of Split --> Stoning Verse --> Liberat Weiß --> Achan --> Ishikozume --> Zenaida --> Zechariah ben Jehoiada --> Emerentiana --> Antonino Fantosati --> The Stoning 

In [2]:
from transformers import RobertaTokenizer, RobertaModel
tokenizer = RobertaTokenizer.from_pretrained('roberta-large')
model = RobertaModel.from_pretrained('roberta-large')

In [4]:
text = "Replace me by any text you'd like."
encoded_input = tokenizer([text, text, 'A little cat'], return_tensors='pt', padding=True)
output = model(**encoded_input)

In [2]:
data_dir = '/media/ron/B008F6C208F6871E/KenshoDerivedWikimediaDataset'
item_tab = pd.read_csv(os.path.join(data_dir, 'item.csv'))
aliase_tab = pd.read_csv(os.path.join(data_dir, 'item_aliases.csv'))

In [11]:
output[1].shape

torch.Size([2, 1024])